# Generated by Django 4.0 on 2021-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='userid',
            field=models.CharField(default=1234, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
