# Generated by Django 4.0 on 2021-12-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_choice_total_vote_alter_choice_vote_controlvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
