# Generated by Django 4.0 on 2021-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0003_choice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ControlVote',
        ),
    ]
